"""Run the pipeline_v2 on real scan data (part 4119905, 5th Stage IBR).

Loads the PLY files generated by stl_to_ply_sampled.py and runs the full
Sprint 4 pipeline with ML classification, 2D conversion, and edge extraction.
Foil tuning is disabled to avoid long auto-calibration runtime.
"""

import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "utils"))

import pipeline_v2

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data")
SCAN_PLY = os.path.join(DATA_DIR, "real_scan_4119905.ply")
CAD_PLY = os.path.join(DATA_DIR, "real_cad_4119905.ply")
PART_NUMBER = "4119905"


def main():
    print("=" * 70)
    print("  REAL DATA PIPELINE RUN — Part 4119905 (5th Stage IBR)")
    print("=" * 70)

    for label, path in [("Scan", SCAN_PLY), ("CAD", CAD_PLY)]:
        if not os.path.exists(path):
            print(f"  ERROR: {label} file not found: {path}")
            sys.exit(1)
        size_mb = os.path.getsize(path) / 1e6
        print(f"  {label}: {path}  ({size_mb:.1f} MB)")

    print()
    t0 = time.time()
    results = pipeline_v2.run_pipeline_v2(
        ply_path=SCAN_PLY,
        cad_path=CAD_PLY,
        part_number=PART_NUMBER,
        enable_foil_tuning=False,
        enable_ml=True,
        enable_2d=True,
        enable_edge_extraction=True,
    )
    total_time = time.time() - t0

    print("\n" + "=" * 70)
    print("  RESULTS SUMMARY")
    print("=" * 70)
    print(f"  Part number:        {PART_NUMBER}")
    print(f"  Total pipeline time: {total_time:.1f}s")
    print(f"  Overall disposition: {results.get('overall_disposition', 'N/A')}")
    print(f"  Total defects:      {results.get('total_defects', 'N/A')}")

    defects = results.get("defects", [])
    if defects:
        print(f"\n  Defect Details ({len(defects)}):")
        for i, d in enumerate(defects[:20]):
            dtype = d.get("ml_type") or d.get("type", "unknown")
            disp = d.get("disposition", "N/A")
            depth = d.get("depth_in", 0)
            length = d.get("length_in", 0)
            zone = d.get("zone", "N/A")
            foil = d.get("foil_number", "?")
            print(f"    [{i+1}] foil={foil} type={dtype} zone={zone} "
                  f"depth={depth:.4f}\" len={length:.4f}\" disp={disp}")
        if len(defects) > 20:
            print(f"    ... and {len(defects) - 20} more")

    sprint4 = results.get("sprint4", {})
    ml = sprint4.get("ml_metrics", {})
    if ml:
        print(f"\n  ML Metrics:")
        for k, v in ml.items():
            print(f"    {k}: {v}")

    edge = sprint4.get("edge_extraction", {})
    if edge:
        print(f"\n  Edge Extraction:")
        print(f"    LE points: {edge.get('le_points', 0)}")
        print(f"    TE points: {edge.get('te_points', 0)}")

    print("=" * 70)
    return results


if __name__ == "__main__":
    main()
