"""Run the pipeline_v2 on real scan data (part 4119905, 5th Stage IBR).

Loads the PLY files generated by stl_to_ply_sampled.py and runs the full
Sprint 4 pipeline with ML classification, 2D conversion, and edge extraction.
Foil tuning is disabled to avoid long auto-calibration runtime.

Exit codes (for scripts / CI):
  0  OK
  1  Unknown error
  2  Missing input files
  3  Pipeline failure
  4  Invalid configuration
  5  Missing optional dependency
"""

import argparse
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "utils"))

import cli_errors
import pipeline_v2

_DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data")
_DEFAULT_SCAN = os.path.join(_DATA_DIR, "real_scan_4119905.ply")
_DEFAULT_CAD = os.path.join(_DATA_DIR, "real_cad_4119905.ply")
PART_NUMBER = "4119905"


def _resolve_paths(args):
    scan = args.scan or os.environ.get("REAL_SCAN_PLY") or _DEFAULT_SCAN
    cad = args.cad or os.environ.get("REAL_CAD_PLY") or _DEFAULT_CAD
    scan = os.path.abspath(scan)
    cad = os.path.abspath(cad)
    return scan, cad


def main():
    parser = argparse.ArgumentParser(
        description="Run pipeline_v2 on real PLY scan + CAD (4119905)."
    )
    parser.add_argument(
        "--scan",
        metavar="PATH",
        help="Scan PLY path (default: data/real_scan_4119905.ply or REAL_SCAN_PLY)",
    )
    parser.add_argument(
        "--cad",
        metavar="PATH",
        help="CAD PLY path (default: data/real_cad_4119905.ply or REAL_CAD_PLY)",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print full traceback on failure",
    )
    args = parser.parse_args()
    scan_ply, cad_ply = _resolve_paths(args)

    print("=" * 70)
    print("  REAL DATA PIPELINE RUN — Part 4119905 (5th Stage IBR)")
    print("=" * 70)

    cli_errors.require_file(scan_ply, "Scan")
    cli_errors.require_file(cad_ply, "CAD")

    for label, path in [("Scan", scan_ply), ("CAD", cad_ply)]:
        size_mb = os.path.getsize(path) / 1e6
        print(f"  {label}: {path}  ({size_mb:.1f} MB)")

    print()
    t0 = time.time()
    try:
        results = pipeline_v2.run_pipeline_v2(
            ply_path=scan_ply,
            cad_path=cad_ply,
            part_number=PART_NUMBER,
            enable_foil_tuning=False,
            enable_ml=True,
            enable_2d=True,
            enable_edge_extraction=True,
        )
    except ImportError as exc:
        cli_errors.fail(
            "A required Python package is missing.",
            code=cli_errors.EXIT_DEPENDENCY_ERROR,
            hint="Run: pip install -r requirements.txt",
            exc=exc,
            verbose=args.verbose,
        )
    except Exception as exc:
        cli_errors.fail(
            "Pipeline run failed. See message below.",
            code=cli_errors.EXIT_PIPELINE_ERROR,
            hint=(
                "Check that PLY files are valid and large enough RAM/disk is available.\n"
                "Try: python run_demo.py (synthetic data) to verify the environment."
            ),
            exc=exc,
            verbose=args.verbose,
        )
    total_time = time.time() - t0

    print("\n" + "=" * 70)
    print("  RESULTS SUMMARY")
    print("=" * 70)
    print(f"  Part number:        {PART_NUMBER}")
    print(f"  Total pipeline time: {total_time:.1f}s")
    print(f"  Overall disposition: {results.get('overall_disposition', 'N/A')}")
    print(f"  Total defects:      {results.get('total_defects', 'N/A')}")

    defects = results.get("defects", [])
    if defects:
        print(f"\n  Defect Details ({len(defects)}):")
        for i, d in enumerate(defects[:20]):
            dtype = d.get("ml_type") or d.get("type", "unknown")
            disp = d.get("disposition", "N/A")
            depth = d.get("depth_in", 0)
            length = d.get("length_in", 0)
            zone = d.get("zone", "N/A")
            foil = d.get("foil_number", "?")
            print(f"    [{i+1}] foil={foil} type={dtype} zone={zone} "
                  f"depth={depth:.4f}\" len={length:.4f}\" disp={disp}")
        if len(defects) > 20:
            print(f"    ... and {len(defects) - 20} more")

    sprint4 = results.get("sprint4", {})
    ml = sprint4.get("ml_metrics", {})
    if ml:
        print(f"\n  ML Metrics:")
        for k, v in ml.items():
            print(f"    {k}: {v}")

    edge = sprint4.get("edge_extraction", {})
    if edge:
        print(f"\n  Edge Extraction:")
        print(f"    LE points: {edge.get('le_points', 0)}")
        print(f"    TE points: {edge.get('te_points', 0)}")

    print("=" * 70)
    return results


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as exc:
        cli_errors.fail(
            "Unexpected error in run_real_data.",
            code=cli_errors.EXIT_UNKNOWN,
            exc=exc,
            verbose="--verbose" in sys.argv or "-v" in sys.argv,
        )
